### PR TITLE
Sbi clear ipi deprecated

### PR DESCRIPTION
**Pull request by konrad-schwarz**
See issue #47.  Note that only the second commit https://github.com/riscv/riscv-sbi-doc/commit/e8a27d65418ad4b2bc7935240a579bc3eca4166a is relevant.

### CODE REVIEW

**Comment by atishp04** [comment]
Now I see that misa_string change was discussed here.

https://github.com/riscv/riscv-sbi-doc/pull/41

Can you remove that commit from this PR ?

**Comment by konrad-schwarz** [comment]
Hi,
so I'm not sure if you accepted my changes or not.

I'm sorry I placed two different issues in the same pull request, but my branch structure and the github web interface left me with no other choice.  I was hoping that the pull request acceptance process would allow "cherry picking" of individual requests.  If not, I would have to restructure my branch structure before resubmitting, or you could simply add the new sentence to the existing document manually.

**Comment by avpatel** [comment]
GitHub PRs are not great for review.

I suggest you send your patches to tech-unixplatformspec@lists.riscv.org mailing list.

I generally send GitHub PR and patch to mailing list.

Regards,
Anup

**Comment by atishp04** [comment]
I will just pick the clear ipi change commit and send a separate PR. Closing this PR as I can not merge this PR.

**Pull request closed without merging**
